# /logger.conf

softname="sample"         #name of your tool 

#COLORS
readonly RED="\033[0;31m"
readonly GREEN="\033[0;32m"
readonly BLUE="\033[0;34m"
readonly YELLOW="\033[0;33m"
readonly NC="\033[0m" # No Color (resets to default)

show_log_inconsole=${show_log_inconsole:-true}  #true or false, if true, logs will be printed in console, otherwise only in log file

readonly logfile="$SCRIPT_DIR/logs/${softname}_${TIMESTAMP}.log" #log file path, you can change it as per your requirement, by default it will create logs folder in the same directory where logger.sh is located and save log files there with name format: sample_2024-06-30_12-00-00.log


