

softname="sample"         #name of your tool 

#COLORS
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly BLUE='\033[0;33m'
readonly NC='\033[0m' # No Color (resets to default)

readonly show_log_inconsole=true  #true or false, if true, logs will be printed in console, otherwise only in log file

readonly logfile="./logs/${softname}_$TIMESTAMP.log"  #log file path

